/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rosiejarvis (https://sketchfab.com/rosiejarvis)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-low-poly-handpainted-environment-pack-0547757625484262a25ea741735682ae
title: Free Low poly Handpainted Environment pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../public/models/trees/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[32.14, 38.41, -15.71]} rotation={[-2.06, -0.09, 2.67]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0, 20.83, -32.02]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh material={materials.lambert7} geometry={nodes.pCube28_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.tree3_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.tree2_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass1_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass2_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass3_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass4_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass5_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.grass6_lambert7_0.geometry} />
          <group position={[-10.07, 5.22, -54.59]} rotation={[-2.86, -0.6, -2.86]} scale={[0.64, 0.64, 0.64]}>
            <group rotation={[0, 0, 0]}>
              <mesh material={materials.lambert7} geometry={nodes.pCube165_lambert7_0.geometry} />
            </group>
            <group rotation={[0, 0, 0]}>
              <mesh material={materials.lambert7} geometry={nodes.pCube13_lambert7_0.geometry} />
            </group>
          </group>
          <mesh material={materials.lambert7} geometry={nodes.plant1_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.rock_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.flower_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.flower4_lambert7_0.geometry} />
          <mesh material={materials.lambert7} geometry={nodes.fern_lambert7_0.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../public/models/trees/scene.gltf')
